package net.kingproductions.splitbornAPI.HelperContainer;

import net.kingproductions.splitbornAPI.EmblemContainer.EmblemID;
import net.kingproductions.splitbornAPI.ItemContainer.Item_Category;
import net.kingproductions.splitbornAPI.ItemContainer.Item_ID;
import net.kingproductions.splitbornAPI.LocationsContainer.Locations;
import net.kingproductions.splitbornAPI.MobContainer.Mob_ID;
import net.kingproductions.splitbornAPI.RarityContainer.Rarities;
import net.kingproductions.splitbornAPI.StatContainer.Stat;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.entity.*;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemStack;
import org.bukkit.util.Vector;

import java.util.List;

public interface HelperProvider {

    void addToFreeActionBar(Player player, String Text);
    boolean completedTutorial(Player player);
    void setEntitySize(LivingEntity entity, double size);
    void DebugMessage(String Message);
    ItemStack DUMMY_GLEAMS();
    List<Location> getBlocksInCuboidAsList(Location pointA, Location pointB);
    int convertMillisInViewableInteger(long millis);
    String formatMobIDToViewableString(Mob_ID mobId);
    String formatEnumName(String input);
    String getGleamSymbol();
    String TaskDescSymbol();
    String getRewardSymbol();
    String getEssenceSymbol();
    String getHeartSymbol();
    String getListingSymbol();
    String getHeatSymbol();
    String getAttackDamageSymbol();
    String getSpeedSymbol();
    String getStaminaSymbol();
    String getEquipmentBonusSymbol();
    String getArrowSymbol();
    String getLocationSymbol();
    String getRangeSymbol();
    String getReelSpeedSymbol();
    String getTerrestrialSymbol();
    String getAquaticSymbol();
    String getMoltenSymbol();
    String getLeapSymbol();
    boolean playerHasActiveQuest(Player player);
    boolean eligibleForUpgrade(int currentXP, int eventXP);
    void fireworkForLevelUpgrade(Player player);
    void upgradePlayersLevel(Player player, int eventXP);
    float ConvertVisualSpeedToUsableFloat(int intSpeed);
    int unclaimedRewardsCount(Player player);
    void handleBuyProcess(Player player, ItemStack BuyItem);
    void applyInventoryLook(Inventory inv, Material material, boolean TopBottom_Full);
    void applyImmortality(Entity e);
    void removeImmortality(Entity e);
    void updatePlayersScoreboard(Player player);
    String getLoreReady_Health(int value);
    String getLoreReady_Stamina(int value);
    String getLoreReady_Speed(int value);
    String getLoreReady_AttackDamage(int value);
    String getLoreReady_Range(int value);
    String getLoreReady_ReelSpeed(int value);
    String getLoreReady_Heat(int value);
    boolean isValidSplitbornItem(ItemStack itemStack);
    Item_ID getItemStacksItemID(ItemStack itemStack);
    Locations getPlayersLocation(Player player);
    String customSerialize(Location location);
    Location customDeserialize(String string);
    Locations getBukkitLocationsSplitbornLocation(Location location);
    int getPlayersTotalDamage(Player player);
    boolean isRPGMob(Entity e);
    void markInventoryChanged(Player player);
    int getPlayersExtraReelSpeed(Player player);
    String formatInteger(int i);
    String getTimeAgo(String longAsString);
    String getPlayersDisplayName(Player player);
    boolean bonusItemIsActive(Player player, Item_ID itemId);
    void fillInventory(Inventory inventory, Material material);
    Rarities getItemsRarity(ItemStack itemStack);
    boolean isWearing(Player player, Item_ID itemId);
    boolean isHolding(Player player, Item_ID itemId);
    boolean inventoryContains(Player player, Item_ID itemId);
    Item_Category getItemCategory(Item_ID itemId);
    void addSplitbornXP(Player player, int Amount);
    String getEmblemIcon(EmblemID emblemID);
    String getEmblem(EmblemID emblemID);
    Arrow spawnBowArrow(Player shooter, Location spawnLocation, Vector direction, int speed, boolean visibleForEveryone);
    boolean blockIsBetween(Location loc1, Location loc2);
    int getPlayersItemCountInWholeInventory(Player player, Item_ID itemId);
    void applyDummyDamage(Player target, int Damage, String CustomName);
    void removeItemAmountFromInventory(Player player, Item_ID itemId, int Amount);
    void modifyPlayersStatTemporarily(Player player, Stat stat, int Amount, int Duration);
    void applyHeat(Player player, int Amount);
    List<Item_ID> getPlayersEquippedBonusItems(Player player);

}
