package net.kingproductions.splitbornAPI.MobContainer;

public enum Mob_ID {

    CHUP,
    ZEMTEX,
    SPEEDY_TURTLE,
    SUNSCALE_AXOLOTL,
    BLOOMFIN_AXOLOTL,
    ABYSSFIN_AXOLOTL,
    MISTFIN_SALMON,
    CHOSNI,
    HOT_KRESS,
    NABY,
    COLOSSAL_KOSWER,
    JUNK_FLY,
    CURSED_BLOOM,
    GLEAM_BUG,
    ELDER_CHUP,
    RIFTWATCHER,
    VOIDSCARRED_CHAMPION,
    ABYSS_CRAWLER,
    PRACTICE_DUMMY,
    UMBRAL,

    BRINECRALWER,
    GLOOMFIN,
    ABYSSAL_ANGLER

}
