package net.kingproductions.splitbornAPI.ItemContainer;

public enum Item_ID {
    MENU,
    GLEAMS,
    SEEDER,
    CHUP_SKIN,
    SWEEPIS_MASK,
    SWEEPIS_TUNIC,
    SWEEPIS_PANTS,
    SWEEPIS_SABATONS,
    CHUP_FLUFF,
    QUIVERING_PEBBLE,
    TIMID_CHARM,
    HALF_EATEN_BERRY,
    CHUPS_TEAR,
    MASTER_KEY,
    ZENTIS_U7,
    FUNNY_SWORD,

    SLEEPY_HAT,
    PAJAMA_CHEST,
    BLANKET_CAPE,
    FLUFFY_SLIPPERS,

    WEIRD_KELP,
    ENERGY_ORB,

    OLD_BROOM,
    WORN_LEATHER_BOOTS,
    HOUSE_SLIPPERS,
    GARDENERS_BOOTS,
    LOOSE_SANDALS,
    HEAVY_WORK_BOOTS


}
