package net.kingproductions.splitbornAPI.ItemContainer;

public enum Item_ID {
    MENU,
    GLEAMS,
    SEEDER,
    CHUP_SKIN,
    SWEEPIS_MASK,
    SWEEPIS_TUNIC,
    SWEEPIS_PANTS,
    SWEEPIS_SABATONS,
    CHUP_FLUFF,
    QUIVERING_PEBBLE,
    TIMID_CHARM,
    HALF_EATEN_BERRY,
    CHUPS_TEAR,
    MASTER_KEY,
    ZENTIS_U7,
    FUNNY_SWORD,

    SLEEPY_HAT,
    PAJAMA_CHEST,
    BLANKET_CAPE,
    FLUFFY_SLIPPERS,

    WEIRD_KELP,
    ENERGY_ORB,


    OLD_BROOM,
    WORN_LEATHER_BOOTS,
    HOUSE_SLIPPERS,
    GARDENERS_BOOTS,
    LOOSE_SANDALS,
    HEAVY_WORK_BOOTS,
    CONFETTI_TELEPORTER,

    MEDIUM_RARE_STEAK,
    WELL_DONE_STEAK,

    LAZY_ROD,
    NOT_SO_LAZY_ROD,
    SLIGHTLY_MOTIVATED_ROD,
    SLOTH_KINGS_ROD,
    ILL_FISH_TOMORROW_ROD,

    ALCHEMICAL_AIR,

    CHALLENGER_HELMET,
    CHALLENGER_CHESTPLATE,
    CHALLENGER_PANTS,
    CHALLENGER_BOOTS,
    CHALLENGERS_EYE,

    CAVE_SHARD,

    CHRONAS_STOPWATCH,
    PRECISIONS_SIGIL,

    CHAMPIONS_KNUCKLES,

    SWEEPIS_RIPENED_MILK,

    CHOSNI_SLAYER,
    MAW_OF_ATTRITION,
    HELM_OF_CHOSNIS_WARD,
    CHESTPLATE_OF_CHOSNIS_WARD,
    LEGGINGS_OF_CHOSNIS_WARD,
    BOOTS_OF_CHOSNIS_WARD,

    COOLING_CRYSTAL,
    UNSTABLE_CORE,
    COAL_CHUNK,

    INFERNAL_CORE,

    EMBER_SWORD,
    STABILIZED_EMBER_SWORD,
    HOT_CROSSBOW,
    STABILIZED_HOT_CROSSBOW,
    SCORCHING_BATTLE_AXE,
    STABILIZED_BATTLE_AXE,
    INFERNO_STAFF,
    STABILIZED_INFERNO_STAFF,
    MOLTEN_RING,
    STABILIZED_MOLTEN_RING,

    UNSTABLE_CAKE,
    STABILIZED_CAKE,

    HEAT_ANCHOR,
    BURNING_CHARM

}
