package net.kingproductions.splitbornAPI.DatabankContainer;

public enum DATABANK_PATHS {

    PERK_1_PATH,
    PERK_2_PATH,
    PERK_3_PATH,

    ALLY_MET_PATH_,
    COMPLETED_QUEST_PATH_,
    SEALED_VOID_GATE_PATH_,
    ACHIEVEMENT_UNLOCKED_PATH_,
    CURIOSITIES_COMPLETED_PATH_,
    ENCOUNTER_COMPLETED_PATH_,
    MYSTERY_COMPLETED_PATH,
    GUARDIAN_DEFEATED_PATH_,

    LEVEL,
    MAX_HEALTH,
    SPEED,
    MAX_STAMINA,
    GLEAMS,
    RANK,
    XP,
    FIRST_JOINED,
    ATTACK_DAMAGE,
    NAME,

    GLOBAL_DISCOVERED_REALMS,
    hearthgrove_completed_quests,
    hearthgrove_allies_met,
    hearthgrove_sealed_void_gate,
    AREA_DISCOVERED_PATH_,

    FRIEND_REQUESTS_ENABLED,
    FRIEND_STATUS_MESSAGES,
    FRIEND_APPEAR_OFFLINE,
    FRIEND_MESSAGE_MODE,
    FRIENDS_SINCE_PATH,

    KILLS_,

    KILL_LOG_LEVEL_,

    LEVEL_CLAIM_,

    ENDER_CHEST_PAGE_,

    ESSENCE_,

    TALENT_VALUE_,
    TALENT_LEVEL_,

    SETTING_CHAT_DROP_ANNOUNCEMENT_TIER_VALUE_I,
    SETTING_CHAT_DROP_ANNOUNCEMENT_TIER_VALUE_II,
    SETTING_CHAT_DROP_ANNOUNCEMENT_TIER_VALUE_III,
    SETTING_CHAT_DROP_ANNOUNCEMENT_TIER_VALUE_IV,
    SETTING_CHAT_DROP_ANNOUNCEMENT_TIER_VALUE_V,

    EMBLEM_ID,
    OWN_EMBLEM_

}
