package net.kingproductions.splitbornAPI.DatabankContainer;

public enum DATABANK_PATHS {

    PERK_1_PATH,
    PERK_2_PATH,
    PERK_3_PATH,

    ALLY_MET_PATH_,
    COMPLETED_QUEST_PATH_,
    SEALED_VOID_GATE_PATH_,
    ACHIEVEMENT_UNLOCKED_PATH_,
    CURIOSITIES_COMPLETED_PATH_,
    EVENT_ATTENDED_COMPLETED_PATH_,
    MYSTERY_COMPLETED_PATH,
    GUARDIAN_DEFEATED_PATH_,

    LEVEL,
    MAX_HEALTH,
    SPEED,
    MAX_STAMINA,
    GLEAMS,
    RANK,
    XP,
    FIRST_JOINED,
    ATTACK_DAMAGE,
    NAME,
    RANGE,
    REEL_SPEED,
    LEAP,
    HEAT,
    EXCAVATION_SPEED,
    EXCAVATION_FORTUNE,

    AREA_DISCOVERED_PATH_,
    LAST_LOCATION_PATH,

    FRIEND_REQUESTS_ENABLED,
    FRIEND_STATUS_MESSAGES,
    FRIEND_APPEAR_OFFLINE,
    FRIEND_MESSAGE_MODE,
    FRIENDS_SINCE_PATH,

    KILLS_,
    DEATH_,

    MINED_,
    MINING_LEVEL_,
    MINING_LEVEL_CLAIMED_,

    KILL_LOG_LEVEL_,

    LEVEL_CLAIM_,

    ENDER_CHEST_PAGE_,

    ESSENCE_,

    TALENT_UNLOCKED_,
    TALENT_OWNED_,

    SETTING_CHAT_DROP_ANNOUNCEMENT_TIER_VALUE_I,
    SETTING_CHAT_DROP_ANNOUNCEMENT_TIER_VALUE_II,
    SETTING_CHAT_DROP_ANNOUNCEMENT_TIER_VALUE_III,
    SETTING_CHAT_DROP_ANNOUNCEMENT_TIER_VALUE_IV,
    SETTING_CHAT_DROP_ANNOUNCEMENT_TIER_VALUE_V,

    EMBLEM_ID,
    OWN_EMBLEM_,

    CLAIMED_SUPPLY_,
    CLAIMED_SUPPLY_COUNT,
    SUPPLY_LEVEL,
    SUPPLY_BONUS_CHANCE,

    INVENTORY,
    UNCLAIMED_ITEMS,
    FRIENDS,
    FRIEND_REQUESTS,

    KILL_LOG_CLAIMED_,

    TOTAL_CATCHES,

    BONUS_ITEM_,

    MINIGAME_HIFE_COMPLETE_,
    MINIGAME_SAIKON_COMPLETE_,

    MINIGAME_HIFE_HIGH_SCORE_,
    MINIGAME_SAIKON_HIGH_SCORE,

    BH_PURCHASE,
    SBC_AMOUNT,
    LADY_CHRONA_REWARD_CLAIMED_,

    KAY_TINFOIL_UNSTABLE_CORES_COMPLETE,
    PURCHASED_AT_KAY_TINFOIL,

    PLAYTIME_SECONDS,

    PIP_REWARD_CLAIMED_,
    PIP_CONTRAPTION_RUSH_COMPLETE_,
    PIP_CONTRAPTION_RUSH_HIGH_SCORE_,

    ASHVEIN_POINTS_,
    JUNK_CHEST_COUNT_,
    LAST_BROMM_COMPLETION,
    FOREMAN_KAELOR_MILESTONE_LEVEL_CLAIMED_,

    PERK_UNLOCKED_,
    PERK_OWNED_,

    OWNING_KILL_EFFECT_,
    UNLOCKED_KILL_EFFECT_,
    SELECTED_KILL_EFFECT_,

    GRUGS_VAULT_LOOTED_GLEAM_REWARD,
    GRUGS_VAULT_LOOTED_KILL_EFFECT,
}
