package net.kingproductions.splitbornAPI.NoteBlockAPIContainer;

public enum NBS_FILE_NAMES {

    ALLY_MET,
    CURIOSITY_FOUND,
    GRUG_TO_BONSAI,
    LEVEL_ASCENDED,
    QUEST_COMPLETE,
    ROTMAW_FIGHT,
    RETRIEVE_SUPPLIES,
    SUPPLY_LEVEL_UP,
    ACHIEVEMENT,
    KILL_LOG_LEVEL_UP,
    DROP_SOUND_TIER_2,
    DROP_SOUND_TIER_3,
    DROP_SOUND_TIER_4,
    DROP_SOUND_TIER_5,
    BOUNCER_PARKOUR_COMPLETE

}
