package net.kingproductions.splitbornAPI.NPC;

public enum NPC_ID {

    BONSAI,GRUG,AREO,ANDREW,STEPHEN,ROTMAW,QUARTERMASTER_BRANNOCK,CYSTEIN,WELPH,LADY_CHRONA,KAY_TINFOIL,CALI_THE_GREAT,VIORICT,DEBY,BROMM,
    FOREMAN_KAELOR,SCRAPPER_FENN,PIP_CINDERWICK
}
